name: build18
dependencies:
- appnope=0.1.0=py27_0
- astropy=1.0.6=np110py27_0
- decorator=4.0.4=py27_0
- ipython=4.0.0=py27_1
- ipython_genutils=0.1.0=py27_0
- nose=1.3.7=py27_0
- numpy=1.10.1=py27_0
- opencv3=3.0.0=nppy27_0
- openssl=1.0.2d=0
- path.py=8.1.2=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- python=2.7.10=2
- python.app=1.2=py27_4
- readline=6.2=2
- setuptools=18.5=py27_0
- simplegeneric=0.8.1=py27_0
- sqlite=3.8.4.1=1
- tbb=4.3_20141023=0
- tk=8.5.18=0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - doxypy==0.4.1
  - imutils==0.3.1
  - ipython-genutils==0.1.0

